---
title: Code ETC
timezone: EST
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: Fibonacci-@users.noreply.github.com
description: 'Jekyll site for Fibonacci-

'
baseurl: 
url: 
twitter_username: 
github_username: 
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
